version: '3.9'

volumes:
  mysql_data:
      driver: local

services:
  mysql:
      image: mysql:latest
      container_name: mysql
      volumes:
        - mysql_data:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      ports:
        - 3306:3306

  keycloak:
      image: quay.io/keycloak/keycloak:latest
      container_name: keycloak
      environment:
        KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
        KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
        KC_DB : mysql
        KC_DB_URL_DATABASE: keycloak
        KC_DB_URL: jdbc:mysql://mysql:3306/keycloak
        KC_DB_USERNAME: ${MYSQL_USER}
        KC_DB_PASSWORD: ${MYSQL_PASSWORD}

      ports:
        - 8080:8080
      command:
        - start-dev
